### ISSUE TITLE
MySQL.jl fails to connect after an ODBC.jl disconnection 

### ISSUE THREAD

**Issue by bmharsha** [JuliaDB/MySQL.jl#10]
Following steps can be performed to reproduce the error 

```
odbc_conn = ODBC.connect("MySQL_DSN")
ODBC.disconnect(odbc_conn)
conn = MySQL.mysql_connect("127.0.0.1", "Username", "Password", "mysqltest")
```

Exact error message can be found below 

```
ERROR: Failed to initialize MySQL database
 in mysql_connect at /home/julia/.julia/v0.3/MySQL/src/handy.jl:19
 in mysql_connect at /home/julia/.julia/v0.3/MySQL/src/handy.jl:43
```

I'm not sure if ODBC.jl is not cleaning up properly (after a disconnection) or its an issue with MySQL.jl , either way, can MySQL.jl handle these kind of errors and continue to function ?

**Comment by ViralBShah** [comment]
This clearly is an ODBC.jl error, right? Seems like it is filed in the wrong repo.

**Comment by bmharsha** [comment]
I was able to reconnect to MySQL through ODBC.jl, I was even able to connect to MySQL database through JDBC.jl right after an ODBC disconnection, so I felt this might be an issue with MySQL.jl

**Comment by ViralBShah** [comment]
Ok. I see what's going on now.

**Comment by nkottary** [comment]
Hi, I was able to reproduce the error with MySQL.jl using mysqlclient shared object. However, this issue does not happen when using the mariadb client shared object.

I would say that this is an issue in the C implementation of mysql rather than in either of ODBC.jl or MySQL.jl. MySQL.jl does nothing beyond calling the mysql_init C API and checking the return value.

If someone needs to use both ODBC.jl and MySQL.jl then the workaround would be to build the client .so file from the mariadb connector source code and add it to path.

**Comment by quinnj** [comment]
Not sure what was going on here. please reopen/comment if this is still an issue.
