### ISSUE TITLE
MySQL v0.2.0 is incompatible with DataFrames v0.11 and prevents a DataFrames upgrade to v0.11.

### ISSUE THREAD

**Issue by ltf-canada** [JuliaDB/MySQL.jl#88]
Occurs on Julia v0.6.1

**Comment by davidanthoff** [comment]
Another option would be to drop the DataFrames dependency entirely and instead just make MySQL.jl an iterable table source. It would make the API slightly more verbose, e.g. something like this:
````julia
dframe = DataFrame(mysql_execute(con, command))
# OR
dframe = mysql_execute(con, command) |> DataFrame
````
But on the flipside it would work with any of the 18 [IterableTables.jl](https://github.com/davidanthoff/IterableTables.jl) sinks. Some examples of things that would just work:
````julia
# IndexedTable
it = table(mysql_execute(con, command))
it = mysql_execute(con, command) |> table

# Pandas.jl
pd = Pandas.DataFrame(mysql_execute(con, command))
it = mysql_execute(con, command) |> Pandas.DataFrame

# CSVFiles.jl
save("myfile.csv", mysql_execute(con, command))
mysql_execute(con, command) |> save("myfile.csv")
````
Plus, you'd get support for DataFrames pre v0.11 and v0.11 for free (and simultaneously, i.e. any given MySQL.jl version would work with either DataFrame version). I guess it would also address #7 in some way.

I have some time next week to get this started if folks think this would be a good idea.

**Comment by quinnj** [comment]
I think it would be fine to have an IterableTables implementation that lives in IterableTables, but I'm against introducing the implementation in this package itself. I have a PR up to properly integrate functionality w/ `Missing`, which will provide native support for missing data in 0.6 and thru Base in 0.7.

I'll have another PR up shortly for proper DataStreams support and then IterableTables support will come for free on top of that through the IterableTables implementation on `Data.Source`s.

Ultimately, I think the correct course of action is to commit to the most natural form of missing data (`Missing`) and allow outside extensions of that to do any other conversions they find necessary. I think it would ultimately be confusing for users, for example, if a package depended on both `Missings` and `DataValues`.

**Comment by nalimilan** [comment]
I agree with @quinnj. `Missing` has just been introduced in Base as the standard way of representing missing data, it would be quite problematic to start adding dependencies on packages which use `DataValue` to many parts of the ecosystem.

**Comment by amellnik** [comment]
The current pull request is here: https://github.com/JuliaDB/MySQL.jl/pull/92

**Comment by davidanthoff** [comment]
I think there would be some benefits going the iterable tables route, in particular in the short to medium run.

One is that the package could support both DataFrames <v0.10 and v0.11 at the same time. So the main problem would be solved (i.e. not blocking the DataFrames v0.11 upgrade anymore), and the story would be fully integrated from a users point of view with the new ``Missing`` story (i.e. if a user is on DataFrames v0.11, he/she will get a ``DataFrame`` that uses ``Missing`` for missing values). At the same time, users that are blocked from upgrading to DataFrames v0.11 (which seems to be mostly everyone right now) would still get updates in this package here because it would be compatible with both versions at the same time. Essentially the package would be decoupled in terms of upper/lower bounds from the DataFrames story. I don't think that is the case with a DataStreams integration, right? With DataStreams users wouldn't get new versions of MySQL.jl, until they have gotten rid of all dependencies that are blocking the DataFrames.jl v0.11 upgrade, right?

Another one is speed on julia 0.6. Not sure how much that is a concern to the users of this package, but it might be important and in that case one would preserve performance for a whole lot of scenarios with the iterable tables approach.

@quinnj is almost right about the "free" support for iterable tables via DataStreams. Right now that doesn't work for DataStreams v0.3.0, mainly because I was just not able to keep up with all the churn there. I plan to add that support back in, but right now it is not there. There is also going to be a performance hit because right now the integration uses the field based streaming story that always has a dynamic dispatch call in the hot code path, plus the general overhead of two glue layers.

> I think it would ultimately be confusing for users, for example, if a package depended on both ``Missings`` and ``DataValues``.

> it would be quite problematic to start adding dependencies on packages which use DataValue to many parts of the ecosystem

So first of, let me stress again that no user would ever notice any of this, so I really don't see how this would be confusing. On the contrary, I go out of my way in the whole iterable tables story to support multiple missing value stories in an entirely transparent way to users, including simultaneous support for all sorts of different approaches. This has worked really, really well over the last year.

> I think it would be fine to have an IterableTables implementation that lives in IterableTables, but I'm against introducing the implementation in this package itself.

That model is really not scalable and a maintenance nightmare. It would be similar to asking all DataStreams integrations to live in DataStreams.jl.

In my mind the iterable tables story is a way to get a lot of stability in terms of integration at this point, while at the same time being fully integrated into all the new stuff around ``Missings`` from a user point of view. The folks that use the native iterable tables integration in their packages right now (e.g. StatsPlots and IndexedTables) all didn't have to do a single thing in terms of the DataFrames v0.10-v0.11 migration, and their packages work with either version. From a user point of view, that seems like a major benefit.

Who is maintaining this package? I would like a clear signal from that person whether a PR that integrates this with the iterable tables would be merged or not before I start working on one.

**Comment by quinnj** [comment]
This package already works w/ DataFrames v0.10, and w/ the PR I just merged (and new tag), now supports DataFrames v0.11, so I don't find the argument to support both simultaneously very compelling.

I think it would be confusing for users who come to the package, look at some of the source code and see both `Missing` and `DataValue` in various places, particularly when Base itself houses `Missing` and promotes it as _the_ canonical way to represent missing data in Julia. Personally, I find it compelling that no other package has had issues w/ using `Missing` to represent missing data. Indeed, in most cases it has drastically simplified implementations and led to much simpler interfaces for end users, as has been the goal.

The fact that users "wouldn't notice any of this" almost seems like a potential source of confusion/bugs to me. All it takes is some code going wrong somewhere and they get some error message mentioning DataValues. Personally, I very much appreciate frameworks/systems/languages that _don't_ try to hide what's going on underneath the covers in case I need to peek and get a clear feel for what's really going on. As you mentioned, there may be non-trivial overhead of glue layers, so best not hide those kinds of things from users.

You mention "being fully integrated into all the new stuff around `Missings`", but I find that really misleading. The fact is it's _not_ integrated w/ `Missings`, and requires inner transformations to and from DataValues. I'd count that similar to declaring a love for tomatoes, but then secretly slipping them out of your hamburger to feed to the dog under the table 😄 .

I think a great path forward would be to move most packages like this and others to support the DataStreams `Data.Source`/`Data.Sink` interfaces natively, and I can help provide first class support for Query.jl to use the `Data.rows(source)` functionality to efficiently convert between Missing and DataValues. That's a win for the ecosystem since packages across the board can use Julia's builtin missing data representation and get efficient interop w/ Query and friends.

In terms of this package, it's been somewhat left by the wayside, but as one of the few active maintainers to JuliaDB and its repos, I'm happy to take up it's maintenance as I'm pretty familiar w/ these kinds of low-level database interfaces. I'd welcome any opinions from @aviks and @iamed2  if they have any additional thoughts on things.

**Comment by quinnj** [comment]
Looking over my last post, I fear I may have come across a little harsh against alternative forms of representing missing data. To be clear, the Nullable/DataValue approach was duly considered, even living inside Base itself for over 3 years! In the end, however, various tradeoffs were considered and due to the end-user and compiler benefits, and various issues w/ Nullables, `Union{T, Missing}` has been chosen as the canonical way to represent missing data in Julia. I feel that is indeed significant. As a package author (and as most other package authors have), I'm excited about this first-class support and have moved quickly to integrate it in my various packages.

That's not to say the `Union{T, Missing}` is perfect; there are indeed tradeoffs and Query.jl seems to have design conflicts with this particular form of missing data. I feel personally that with enough effort and creativity, it could be made to work, even if only 95% of use-cases were covered (see PR [here](https://github.com/davidanthoff/Query.jl/pull/155) for ideas of doing just that) , but I also recognize that @davidanthoff feels the DataValue approach provides enough benefit across other packages and wishes to keep that. And I respect that. That's why I suggested working together to provide the best possible integration between `Data.rows(source)` and the IterableTables interface; I do think we could make the transformation efficient enough to make user-impact negligible. That would lead to the ideal situation I mentioned above, where packages wishing to hook into ecosystem table IO can implement the DataStreams interfaces and then automatically get support for the functionality that Query et al. provide.

**Comment by davidanthoff** [comment]
Just on the Query.jl parts: I had a version of Query last year that tried to convert the missing representation on the way in and then on the way out for each Query.jl. Essentially the design was similar to what I think you are proposing  when you write "and I can help provide first class support for Query.jl to use the Data.rows(source) functionality to efficiently convert between Missing and DataValues": back then the iterable tables interface was based on ``Nullable``, but in Query.jl I wanted to use ``DataValue`` so that users would get a nice and convenient interface. The whole thing was a complete mess and never worked well. There are some really subtle and difficult problems that I initially thought one could just solve eventually, but after a couple of weeks of trying I gave up. The whole thing would get even more complicated with the new standalone macros, because it is much more difficult to say up-front where a query starts and ends. I guess my main message is, don't underestimate the difficulties with this approach, I've been there and tried it and it was not pretty. Doesn't mean it is impossible, but I've certainly run out of ideas on that front.

As I wrote over in my reply to your https://github.com/davidanthoff/Query.jl/pull/155 PR, it is really clever. But it would forever tie Query.jl to rely on inference, and in my mind that is a no-starter. Query's current reliance on inference is by far the biggest design problem with it. I think at this point I have a complete plan to solve that, so I'm really not keen to add something that would cement the reliance on inference into the system.

I should also add, ``DataValue`` also has lots of problems. That is where we are, we don't have a good missing value story that works for all the important use cases we have at this point. That is obviously no ones fault, the whole thing is just tricky. 

I would suggest that if we want to continue the discussion re Query, lets do it in an issue over at the Query.jl repo.
